### ISSUE TITLE
ERROR: cannot import name 'dgp_educ_wages' from 'src.dgp'

### ISSUE THREAD

**Issue by jbdatascience** [matteocourthoud/Blog-Posts#1]
The line:
from src.dgp import dgp_educ_wages

throws me this error:
ImportError: cannot import name 'dgp_educ_wages' from 'src.dgp' (/content/Blog-Posts/src/dgp.py)

And indeed, searching through the file dgp.py, I could not find 'dgp_educ_wages'

**Comment by matteocourthoud** [comment]
Thanks Jan! I forgot to push the new version of src/dgp.py. Should work now!

**Comment by jbdatascience** [comment]
I will try it out later today and let you know the result

**Comment by jbdatascience** [comment]
Now everything works fine. Thank you !

**Comment by matteocourthoud** [comment]
Perfect! I am closing the issue, but thanks again.
